---
# tasks file for ansible-role-monit

- include_vars: "{{ ansible_os_family }}.yml"

- assert:
    msg: monit_conf_extra_include_directories must be sequence, or list
    that:
      - monit_conf_extra_include_directories is sequence

- assert:
    msg: "`path` of item in monit_conf_extra_include_directories must exist and must be string"
    that:
      - "'path' in item"
      - item.path is string
  with_items: "{{ monit_conf_extra_include_directories }}"

- assert:
    msg: "`state` of item in monit_conf_extra_include_directories must exist and must be either `enabled` or `disabled`"
    that:
      - "'state' in item"
      - item.state == 'enabled' or item.state == 'disabled'
  with_items: "{{ monit_conf_extra_include_directories }}"

- assert:
    msg: item in monit_conf_extra_include_directories must have `path` as key
    that:
      - "'path' in item"
  with_items: "{{ monit_conf_extra_include_directories }}"

- assert:
    msg: "key `{{ item.key }}` must have a key, `state` and the key must be either `present` or `absent`"
    that:
      - "'state' in item.value"
      - item.value.state == 'present' or item.value.state == 'absent'
  with_dict: "{{ monit_rc }}"

- assert:
    msg: "key `{{ item.key }}` must have a key, `content` when `state` is `present`, and the key must be a string"
    that:
      - "'content' in item.value"
      - item.value.content is string
  when:
    - item.value.state == 'present'
  with_dict: "{{ monit_rc }}"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create monit_conf_include_dir
  file:
    path: "{{ monit_conf_include_dir }}"
    mode: 0755
    state: directory

- name: Create monirc fragments
  template:
    src: monitrc.fragment.j2
    dest: "{{ monit_conf_include_dir }}/{{ item.key }}.monitrc"
    mode: 0600
  with_dict: "{{ monit_rc }}"
  when:
    - item.value.state == 'present'

- name: Remove monitrc fragments
  file:
    path: "{{ monit_conf_include_dir }}/{{ item.key }}.monitrc"
    state: absent
  with_dict: "{{ monit_rc }}"
  when:
    - item.value.state == 'absent'

- name: Create monit.conf
  template:
    src: monitrc.j2
    dest: "{{ monit_conf_file }}"
    mode: 0600
    backup: yes
  register: register_monitrc
  notify: Restart monit

- name: Remove old monit.conf files
  shell: "find {{ monit_conf_dir }} -iname '{{ monit_conf_file }}.*@*~' -type f | sort | head -n 3 | xargs -r -n 1 rm"
  changed_when: false
  when: register_monitrc.changed

- name: Validate monit.conf
  command: "monit -t -c {{ monit_conf_file }}"
  changed_when: false
  when: register_monitrc.changed

- name: Create pre-defined script
  copy:
    dest: "{{ monit_script_path }}/{{ item }}"
    src: "{{ item }}"
    mode: 0755
  with_items: "{{ monit_scripts }}"

- name: Start monit
  service:
    name: "{{ monit_service }}"
    enabled: true
    state: started
